"""add bank_name to users v2

Revision ID: 5266472ac20f
Revises: 725e1ea9a518
Create Date: 2026-07-14 15:51:09.662064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5266472ac20f'
down_revision: Union[str, Sequence[str], None] = '725e1ea9a518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_name')
    # ### end Alembic commands ###
