"""add loans table

Revision ID: 53385f7d4e8b
Revises: 9deccd44dc24
Create Date: 2026-06-26 16:50:01.247766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53385f7d4e8b'
down_revision: Union[str, Sequence[str], None] = '9deccd44dc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Loan_id'), 'Loan', ['id'], unique=False)
    op.create_index(op.f('ix_Loan_user_id'), 'Loan', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Loan_user_id'), table_name='Loan')
    op.drop_index(op.f('ix_Loan_id'), table_name='Loan')
    op.drop_table('Loan')
    # ### end Alembic commands ###
