"""add banks table

Revision ID: 9f9fbe812827
Revises: 53385f7d4e8b
Create Date: 2026-06-28 16:12:32.354627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9fbe812827'
down_revision: Union[str, Sequence[str], None] = '53385f7d4e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BankLoanDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('processing_fee', sa.Float(), nullable=False),
    sa.Column('max_tenure_months', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BankLoanDetails_id'), 'BankLoanDetails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BankLoanDetails_id'), table_name='BankLoanDetails')
    op.drop_table('BankLoanDetails')
    # ### end Alembic commands ###
